name: Workflow B
on:
  pull_request:
    branches:
      - develop
      - master
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  workflow_call:

jobs:
  Jobs-B:
    name: Job B
    runs-on: ubuntu-latest
    env:
      TRIGGERING_REPOSITORY: ${{ github.action_repository }}
      TRIGGERING_EVENT_REPOSITORY: ${{ github.event.repository.name }}
    steps:
      - name: Check out common code
        uses: actions/checkout@v4
        with:
          repository: gladykov/TestRepo
          path: common
      - name: Show me
        run: |
          ls
          ls common
      - name: Run action from private repo
        uses: ./common/.github/workflows/prepare_common_repo.yml
