name: Workflow B
on:
  pull_request:
    branches:
      - develop
      - master
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  workflow_call:

jobs:
  Jobs-B:
    name: Job B
    runs-on: ubuntu-latest
    steps:
      - name: Check out common code
        uses: actions/checkout@v4
        repository: gladykov/TestRepo2
        path: common
      - name: Run action from private repo
        uses: ./.github/prepare_common_repo.yml
