name: Workflow B
on:
  pull_request:
    branches:
      - develop
      - master
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  workflow_call:

jobs:
  Jobs-B:
    name: Job B
    runs-on: ubuntu-latest
    env:
      TRIGGERING_REPOSITORY: ${{ github.action_repository }}
      TRIGGERING_EVENT_REPOSITORY: ${{ github.event.repository.name }}
    steps:
      - name: Hello World B from TestRepo2
        run: exit 1
      - name: try composite
        uses: gladykov/TestRepo/.github/workflows/prepare_common_repo.yml@main
        secrets: inherit


